[package]
name = "petitset"
description = "An ordered set data structure, optimized for stack-allocated storage of a tiny number of elements with a fixed cap."
version = "0.0.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com"
repository = "https://github.com/leafwing-studios/petitset"
license = "MIT + APACHE"
edition = "2021"
categories = ["data-structures"]
keywords = ["set"]
exclude = ["tools/**/*", "github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci"]

[dev-dependencies]
criterion = "0.3"

[lib]
name = "petitset_lib"
path = "src/lib.rs"
